name: Inclusive Organization
on:
  push:
    branches: [main]

jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite contributor to the organization
        uses: lekterable/inclusive-organization-action@v1.1.0
        with:
          organization: strawberry-graphql
          team: strawberry-contributors
          comment: Thanks for your first contribution to Strawberry! You've been
            invited to our organization, check your emails for the invite ðŸ˜Š

            Also, feel free to request a sticker by filling this form ðŸ‘‰
            https://forms.gle/dmnfQUPoY5gZbVT67
        env:
          ACCESS_TOKEN: ${{ secrets.INCLUSIVE_ORGANIZATION_TOKEN }}
