name: ðŸ‘¥ Invite contributors

on:
  push:
    branches:
      - main

jobs:
  invite-contributor:
    name: Invite contributors
    runs-on: ubuntu-latest

    steps:
      - name: Invite contributors
        uses: strawberry-graphql/invite-to-org-action@260b05042142d5cc1af3f87a0547f72389df7fd8 # v4
        with:
          organisation: "strawberry-graphql"
          comment: |
            Thanks for contributing to Strawberry! ðŸŽ‰ You've been invited to join
            the Strawberry GraphQL organisation ðŸ˜Š

            You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

            And don't forget to join our discord server: https://strawberry.rocks/discord ðŸ”¥
          team-slug: "strawberry-contributors"
          github-token: ${{ secrets.BOT_TOKEN }}
